apiVersion: v1
kind: ServiceAccount
metadata:
    name: autoscaler
    namespace: ray
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: autoscaler
rules:
- apiGroups: [""]
  resources: ["pods", "pods/status", "pods/exec", "namespaces", "serviceaccounts"]
  verbs: ["get", "watch", "list", "create", "delete", "patch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "watch", "list", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: autoscaler
subjects:
- kind: ServiceAccount
  name: autoscaler
  namespace: ray
roleRef:
    kind: ClusterRole
    name: autoscaler
    apiGroup: rbac.authorization.k8s.io